version: "3.8"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - udemyClientID=test
      - udemyClientSecret=test
      # - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=0
      - DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/hello_flask_prod
      - PORT=5000

    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_prod

volumes:
  postgres_data_prod:
