version: "3.8"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./services/web/.env

    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_prod

volumes:
  postgres_data_prod:
